version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "npm"
      include: "scope"
    reviewers:
      - "basnijholt"
    open-pull-requests-limit: 5

  # Enable version updates for Python pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "pip"
      include: "scope"
    reviewers:
      - "basnijholt"
    open-pull-requests-limit: 5

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    reviewers:
      - "basnijholt"
    open-pull-requests-limit: 3
