repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-yaml
      - id: debug-statements
      - id: check-ast
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.4"
    hooks:
      - id: ruff
        exclude: docs/source/conf.py|ipynb_filter.py
        args: ["--fix"]
      - id: ruff-format
        exclude: docs/source/conf.py|ipynb_filter.py
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.0"
    hooks:
      - id: mypy
        exclude: ipynb_filter.py|docs/source/conf.py
        additional_dependencies:
          - types-setuptools
          - pandas-stubs
          - types-psutil
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|scss|md|yaml|yml)$
        exclude: |
          (?x)^(
              frontend/dist/.*|
              frontend/node_modules/.*|
              .*\.min\.(js|css)$
          )$
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd frontend && npm run lint'
        language: system
        files: ^frontend/src/.*\.(ts|tsx)$
        pass_filenames: false
